[package]
name = "zuul-static-parser-study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
glob = "0.3.1"
hashlink = "0.8"
log = "0.4.21"
path-absolutize = "3.1.1"
pathdiff = "0.2.1"
phf = { version = "0.11.2", features = ["macros"] }
shellexpand = "3.1.0"
yaml-rust2 = "0.8.0"
# chumsky = "0.8.0"
# env_logger = "0.9.0"
# ropey = "1.5.0"
# serde_json = "1.0.78"
# tokio = { version = "1.17.0", features = ["full"] }
# tower-lsp = { version = "0.20.0", features = ["proposed"]}
# serde = { version = "1.0", features = ["derive"] }
# dashmap = "5.1.0"
# log = "0.4.14"
# im-rc = "15.0.0"
